# Generated by Django 4.1.2 on 2023-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Technology', 'Technology')], default='uncategorized', max_length=100),
        ),
    ]
